/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF} from "@react-three/drei";
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import {useLoader } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF("assets/Home.glb");
  const ground = useLoader(TextureLoader, 'assets/Ground.jpg')

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ground.geometry}
        material={nodes.Ground.material}
        position={[4.36, 0, 5.01]}>
            <meshBasicMaterial map={ground} map-flipY={false} />
            {/* <primitive object={props.model} /> */}
        </mesh>
    </group>
  );
}

useGLTF.preload("assets/Home.glb");
